# Generated by Django 3.1.1 on 2020-11-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bloguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
